In [81]:
import numpy as np
import pandas as pd

In [127]:
x = pd.read_csv('wineQualityRed_train.csv',';',header = 0)

In [128]:
df = pd.DataFrame(x)

In [129]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0              10.6             0.280         0.39            15.5      0.069   
1               9.4             0.300         0.56             2.8      0.080   
2              10.6             0.360         0.59             2.2      0.152   
3              10.6             0.360         0.60             2.2      0.152   
4              10.6             0.440         0.68             4.1      0.114   
...             ...               ...          ...             ...        ...   
1114            6.2             0.600         0.08             2.0      0.090   
1115            5.9             0.550         0.10             2.2      0.062   
1116            6.3             0.510         0.13             2.3      0.076   
1117            5.9             0.645         0.12             2.0      0.075   
1118            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                     6.0                  23.0  1.00260  3.12       0.66   
1                     6.0                  17.0  0.99640  3.15       0.92   
2                     6.0                  18.0  0.99860  3.04       1.05   
3                     7.0                  18.0  0.99860  3.04       1.06   
4                     6.0                  24.0  0.99700  3.06       0.66   
...                   ...                   ...      ...   ...        ...   
1114                 32.0                  44.0  0.99490  3.45       0.58   
1115                 39.0                  51.0  0.99512  3.52       0.76   
1116                 29.0                  40.0  0.99574  3.42       0.75   
1117                 32.0                  44.0  0.99547  3.57       0.71   
1118                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.2        5  
1        11.7        8  
2         9.4        5  
3         9.4        5  
4        13.4        6  
...       ...      ...  
1114     10.5        5  
1115     11.2        6  
1116     11.0        6  
1117     10.2        5  
1118     11.0        6  

[1119 rows x 12 columns]

In [130]:
Y = df['quality']

In [131]:
Y.head()

0    5
1    8
2    5
3    5
4    6
Name: quality, dtype: int64

In [132]:
X = df[['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol']]

In [133]:
X.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0           10.6              0.28         0.39            15.5      0.069   
1            9.4              0.30         0.56             2.8      0.080   
2           10.6              0.36         0.59             2.2      0.152   
3           10.6              0.36         0.60             2.2      0.152   
4           10.6              0.44         0.68             4.1      0.114   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                  6.0                  23.0   1.0026  3.12       0.66   
1                  6.0                  17.0   0.9964  3.15       0.92   
2                  6.0                  18.0   0.9986  3.04       1.05   
3                  7.0                  18.0   0.9986  3.04       1.06   
4                  6.0                  24.0   0.9970  3.06       0.66   

   alcohol  
0      9.2  
1     11.7  
2      9.4  
3      9.4  
4     13.4

In [134]:
from sklearn import linear_model

In [135]:
model = linear_model.LinearRegression()

In [136]:
model.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [137]:
test = pd.read_csv('wineQualityRed_test.csv',';',header = 0)

In [138]:
test_df = pd.DataFrame(test)

In [139]:
test_df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                    34   0.9978  3.51       0.56   
1                 25.0                    67   0.9968  3.20       0.68   
2                 15.0                    54   0.9970  3.26       0.65   
3                 17.0                    60   0.9980  3.16       0.58   
4                 11.0                    34   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [140]:
X_test = test_df[['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol']]
Y_test = test_df['quality']

In [141]:
X_test.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                    34   0.9978  3.51       0.56   
1                 25.0                    67   0.9968  3.20       0.68   
2                 15.0                    54   0.9970  3.26       0.65   
3                 17.0                    60   0.9980  3.16       0.58   
4                 11.0                    34   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [142]:
Y_preds= model.predict(X_test)

In [143]:
comparison = pd.DataFrame({'  Actual Quality ': Y_test, '   Predicted Quality': Y_preds})

In [144]:
comparison

Actual Quality      Predicted Quality
0                    5              4.940841
1                    5              5.167903
2                    5              5.214698
3                    6              5.649335
4                    5              4.940841
..                 ...                   ...
475                  5              5.379752
476                  5              5.752668
477                  6              6.660519
478                  5              5.379752
479                  6              5.481773

[480 rows x 2 columns]

In [145]:
from sklearn import metrics

In [146]:
print('Mean Squared Error:', metrics.mean_squared_error(Y_test, Y_preds))

Mean Squared Error: 0.4463021333444592


In [147]:
total = 0;
for i in range (0,len(Y_test)):
    total = total + (Y_test[i] - Y_preds[i])**2
total

214.22502400534034

In [148]:
mean_squared_error = total/len(Y_test)

In [149]:
mean_squared_error

0.44630213334445906

In [150]:
import matplotlib.pyplot as plt

In [151]:
coeff_df = pd.DataFrame(model.coef_, ['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol'], columns=['Coefficient'])
coeff_df

Coefficient
fixed acidity           -0.005731
volatile acidity        -1.071489
citric acid             -0.063048
residual sugar           0.010234
chlorides               -1.940448
free sulfur dioxide      0.003516
total sulfur dioxide    -0.002155
density                -26.891259
pH                      -0.634244
sulphates                1.241948
alcohol                  0.267755

In [152]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0           10.6              0.28         0.39            15.5      0.069   
1            9.4              0.30         0.56             2.8      0.080   
2           10.6              0.36         0.59             2.2      0.152   
3           10.6              0.36         0.60             2.2      0.152   
4           10.6              0.44         0.68             4.1      0.114   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                  6.0                  23.0   1.0026  3.12       0.66   
1                  6.0                  17.0   0.9964  3.15       0.92   
2                  6.0                  18.0   0.9986  3.04       1.05   
3                  7.0                  18.0   0.9986  3.04       1.06   
4                  6.0                  24.0   0.9970  3.06       0.66   

   alcohol  quality  
0      9.2        5  
1     11.7        8  
2      9.4        5  
3      9.4        5  
4     13.4        6

In [153]:
df['quality'].value_counts()

6    462
5    448
7    150
4     37
8     13
3      9
Name: quality, dtype: int64

In [154]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [155]:
df['quality_label'] = df['quality'].map({3 : 'bad', 4 :'bad', 5: 'bad',
                                      6: 'good', 7: 'good', 8: 'good'})

In [156]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0           10.6              0.28         0.39            15.5      0.069   
1            9.4              0.30         0.56             2.8      0.080   
2           10.6              0.36         0.59             2.2      0.152   
3           10.6              0.36         0.60             2.2      0.152   
4           10.6              0.44         0.68             4.1      0.114   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                  6.0                  23.0   1.0026  3.12       0.66   
1                  6.0                  17.0   0.9964  3.15       0.92   
2                  6.0                  18.0   0.9986  3.04       1.05   
3                  7.0                  18.0   0.9986  3.04       1.06   
4                  6.0                  24.0   0.9970  3.06       0.66   

   alcohol  quality quality_label  
0      9.2        5           bad  
1     11.7        8          good  
2      9.4        5           bad  
3      9.4        5           bad  
4     13.4        6          good

In [157]:
df['quality_label'].value_counts()

good    625
bad     494
Name: quality_label, dtype: int64

In [158]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
logistic = LogisticRegression()


In [184]:
X = df[['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol']]

In [185]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['quality_label'] = le.fit_transform(df['quality_label'])

df['quality_label'].value_counts

<bound method IndexOpsMixin.value_counts of 0       0
1       1
2       0
3       0
4       1
       ..
1114    0
1115    1
1116    1
1117    0
1118    1
Name: quality_label, Length: 1119, dtype: int64>

In [186]:
Y = df['quality_label']

In [187]:
logistic.fit(X,Y)

C:\Users\giris\desktop\sample_project_1\enc\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [188]:
test = pd.read_csv('wineQualityRed_test.csv',';',header = 0)
test_df = pd.DataFrame(test)

In [189]:
test_df['quality_label'] = test_df['quality'].map({3 : 'bad', 4 :'bad', 5: 'bad',
                                      6: 'good', 7: 'good', 8: 'good'})

In [190]:
le = LabelEncoder()

test_df['quality_label'] = le.fit_transform(test_df['quality_label'])


In [191]:
X_test = test_df[['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol']]
Y_test = test_df['quality_label']


In [192]:
Y_test,Y_preds

(0      0
 1      0
 2      0
 3      1
 4      0
       ..
 475    0
 476    0
 477    1
 478    0
 479    1
 Name: quality_label, Length: 480, dtype: int32,
 array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
        0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
        1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 1, 0, 0, 0, 0

In [193]:
logistic.score(X_test,Y_test)

0.7125

In [194]:
print(confusion_matrix(Y_test, Y_preds))

[[191  59]
 [ 79 151]]


In [195]:

linear = linear_model.LinearRegression()
linear.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [196]:
Y_preds = linear.predict(X_test)

In [197]:
Y_preds,Y_test

(array([ 0.22007343,  0.3018336 ,  0.32442652,  0.46296118,  0.22007343,
         0.23344209,  0.20829731,  0.37656718,  0.37224313,  0.53680972,
         0.21763693,  0.53680972,  0.28119204,  0.88378276,  0.30282088,
         0.32742528,  0.6238965 ,  0.57807506,  0.19356705,  0.55941072,
         0.40997117,  0.39471072,  0.62984247,  0.28391585,  0.49207402,
         0.41905546,  0.46139856,  0.62984247,  0.22659051,  0.39676317,
         0.27656095,  0.45992059,  0.26592995,  0.25811259,  0.34573388,
         0.31904484,  0.53931639,  0.59886606, -0.01285229,  0.60289024,
         0.60289024,  0.21673536,  0.64315389,  0.86080313,  0.29253887,
         0.78114167,  0.01438881,  0.42121225,  0.4031456 ,  0.27836115,
         0.37612223,  0.43604167,  0.45188717,  0.27453888,  0.52451259,
         0.31111464,  0.51050211,  0.37422199,  0.36363024,  0.32941789,
         0.33750956,  0.14070175,  0.37767669,  0.25983478,  0.39874597,
         0.39874597,  0.35441579,  0.48614983,  0.7

In [198]:
from sklearn.svm import SVC
support = SVC()

In [199]:
support.fit(X,Y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [200]:
Y_preds = support.predict(X_test)

In [201]:
Y_preds,Y_test

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
        1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
        1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
        0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
        1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
        0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
        1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
        0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 

In [202]:
support.score(X_test,Y_test)

0.6229166666666667

In [203]:
print(confusion_matrix(Y_test, Y_preds))

[[ 89 161]
 [ 20 210]]


In [204]:
from sklearn.naive_bayes import GaussianNB 
naive = GaussianNB()

In [205]:
naive.fit(X,Y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [206]:
Y_preds = naive.predict(X_test)

In [207]:
Y_test,Y_preds

(0      0
 1      0
 2      0
 3      1
 4      0
       ..
 475    0
 476    0
 477    1
 478    0
 479    1
 Name: quality_label, Length: 480, dtype: int32,
 array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
        0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
        1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 1, 0, 0, 0, 0

In [208]:
naive.score(X_test,Y_test)

0.7125

In [210]:
A = confusion_matrix(Y_test, Y_preds)
A

array([[191,  59],
       [ 79, 151]], dtype=int64)

In [217]:
naive_acc = (A[0][0] + A[1][1])/(A[0][0] + A[0][1] + A[1][0] + A[1][1])
naive_prec = A[0][0]/(A[0][0] + A[0][1])
naive_recall = A[0][0]/(A[0][0] + A[1][0])
naive_f1 = 2*naive_recall*naive_prec/(naive_recall + naive_prec)
naive_sensitivity = naive_recall = A[1][1]/(A[0][1] + A[1][1])

In [218]:
naive_acc,naive_prec,naive_recall,naive_f1

(0.7125, 0.764, 0.719047619047619, 0.7346153846153844)

In [219]:
print(metrics.classification_report(Y_test,Y_preds))

              precision    recall  f1-score   support

           0       0.71      0.76      0.73       250
           1       0.72      0.66      0.69       230

    accuracy                           0.71       480
   macro avg       0.71      0.71      0.71       480
weighted avg       0.71      0.71      0.71       480

